### ISSUE TITLE
Set up toolbox

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-toolbox#1]
## Tasks

Todo

Monorepo:

- [x] set up monorepo
- [x] add turbo or such like

Tools:

- [x] migrate responsive resizer code

Code:

- [x] write script to export and stub docs code
- [ ] commit code
- [ ] document
